### ISSUE TITLE
build-maven-semver-cache-assets only works for jars

### ISSUE THREAD

**Issue by rs017991** [aegershman/pipeline-tasks#11]
https://github.com/aegershman/pipeline-tasks/blob/5c017f8722ccfc32227269655c955ad63755899f/build-maven-semver-cache-assets/task.sh#L32

This script hardcodes 'jar' in the glob, ignoring the actual packaging type. This fails when war packaging is used, for example.

None of the other scripts appear to have the issue, just **maven-semver-cache-assets**

**Comment by aegershman** [comment]
closing in preparation of archiving this repo
