### ISSUE TITLE
Support for Spring multi module projects

### ISSUE THREAD

**Issue by febinrejoe** [aegershman/pipeline-tasks#8]
I've got a multi-module project https://spring.io/guides/gs/multi-module/ it has a rest service and a library in it. The Concourse build for this project is failing here https://github.com/aegershman/pipeline-tasks/blob/master/build-maven-semver-cache-assets/task.sh#L32 as the script is looking for the artifact in /project/target/*.jar whereas in my case it will be in /project/<Service Name>/target/*.jar

Is there a way to pass the path of artifacts as a parameter?

**Comment by aegershman** [comment]
I promise I haven't forgotten about you, my man. I'm sorry, just hasn't been on the top list of priorities. There is not currently a way to pass the path of artifacts as a parameter. Have you come up with any temporary workaround? Or is this still an outstanding blocker?

**Comment by febinrejoe** [comment]
not a problem, we are re-thinking about the multi-module project setup, so this is not an urgent request.

**Comment by aegershman** [comment]
closing in preparation of archiving this repo
